AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Style/ConditionalAssignment:
    Enabled: true
Style/StringLiterals:
    Enabled: true
Style/RedundantReturn:
    Enabled: true
Style/Documentation:
    Enabled: true
Style/WordArray:
    Enabled: true
Style/MutableConstant:
    Enabled: true
Style/SignalException:
    Enabled: true
Style/MissingRespondToMissing:
    Enabled: true
Style/MethodMissingSuper:
    Enabled: true
Style/FrozenStringLiteralComment:
    Enabled: false
Style/EmptyMethod:
    Enabled: true
Metrics/CyclomaticComplexity:
    Enabled: true
Metrics/AbcSize:
    Enabled: true
Layout/LineLength:
    Max: 110
Layout/IndentationWidth:
    Width: 4
Bundler/OrderedGems:
    Enabled: false
